[profile.default]
  solc = "0.8.28"
  src = "src"
  out = "out"
  libs = ["lib"]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[doc]
  ignore = ["**/*.t.sol"]
  out = "docs"
  repository = "https://github.com/Legion-Team/evm-contracts"

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
  arbitrum = "${ARBITRUM_RPC_URL}"
  arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
  sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
  arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
  arbitrum_sepolia = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
