name: Forge CI

on:
  push:
  pull_request:
    branches:
      - master
      - dev

env:
  FOUNDRY_PROFILE: ci

jobs:
  analyze:
    name: Run Slither Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Slither
      uses: crytic/slither-action@v0.4.0
      id: slither
      with:
        node-version: 16
        fail-on: high
        slither-args: --skip-assembly

  forge-test:
    name: Run Forge Tests and Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Check formatting
        run: |
          forge fmt --check
        id: fmt

      - name: Check snapshot
        run: |
          forge snapshot --check --tolerance 1
        id: snapshot

  forge-coverage:
    name: Run Coverage Reporting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install

      - name: Install lcov
        run: |
          sudo apt-get install lcov
        id: lcov

      - name: Run coverage
        run: |
          forge coverage --no-match-coverage "(script|test|lib|mocks)" --report summary --report lcov

      - name: Prune coverage
        run: |
          lcov --remove ./lcov.info -o ./lcov-filtered.info
          
